### ISSUE TITLE
click: true and tap: true, bug ?

### ISSUE THREAD

**Issue by angelru** [cubiq/iscroll#878] opened 2015-03-25 09:59 UTC
Hello, i have a problem, tap: true and click: true, click twice in android 4.3  4.2. 4.1.
in android 4.4 works well. how can I fix it?

**Comment by laziel** [comment] 2015-05-26 06:00
Hi. Isn't it same with #674 #361 ?

**Comment by angelru** [comment] 2015-05-26 07:53
yes! I had not seen it

**Comment by davidpfahler** [comment] 2015-05-27 14:51
Closing because this issue is a duplicate of #361.

**Closed by davidpfahler** 2015-05-27 14:51 UTC
