### ISSUE TITLE
Clicks firing twice

### ISSUE THREAD

**Issue by nsbasic** [cubiq/iscroll#674] opened 2014-04-10 15:09 UTC
We've recently switched in iScroll 5. The initial problem we had was that clicks were not happening on Android, but were OK on other platforms.

The solution was to add click:true to the initialization. That fixed Android, but we now have two clicks firing on other platforms.

Changing to ontap is not practical: there is a huge amount of legacy code. Can this switch be made Android only?

**Comment by davidpfahler** [comment] 2015-05-27 14:52
Closing because this issue is a duplicate of #361.

**Closed by davidpfahler** 2015-05-27 14:52 UTC

**Comment by raghav1086** [comment] 2018-05-15 07:59
@orenagiv Thanks very much. Life saving tip 👍 💯
